/** PO lifecycle statuses (Sheet 02 + 09) */
const PO_STATUSES = [
  'DRAFT',
  'SUBMITTED',
  'APPROVED',
  'REJECTED',
  'RELEASED',
  'PART_SUPPLIED',
  'CLOSED',
  'CANCELLED',
  /** @deprecated legacy — migrate to RELEASED */
  'RAISED',
  /** @deprecated legacy — migrate to PART_SUPPLIED */
  'PARTIAL',
];

/** Legacy alias kept for migration */
const LEGACY_PO_RAISED = 'RAISED';
const LEGACY_PO_PARTIAL = 'PARTIAL';

/** Vehicle stock lifecycle (Sheet 07 + 09) */
const VEHICLE_STATUSES = [
  'IN_TRANSIT',
  'ARRIVED',
  'RECEIVED',
  'EXCEPTION',
  'RECEIPT_ACCEPTED',
  'HOLD',
  'PDI_PENDING',
  'PDI_PASS',
  'PDI_FAIL',
  'PDI_HOLD',
  'AVAILABLE',
  'RESERVED',
  'BOOKED',
  'INVOICED',
  'DELIVERY_READY',
  'DELIVERED',
  'BLOCKED',
  'DAMAGED',
  'WORKSHOP',
  'DEMO',
  'DISPLAY',
  'TEST_DRIVE',
];

/** Legacy VehicleStock.status values */
const LEGACY_STOCK_STATUSES = ['FRESH_STOCK', 'DEMO', 'RESERVED', 'SOLD', 'IN_TRANSIT'];

const PO_STATUS_TRANSITIONS = {
  DRAFT: ['SUBMITTED', 'CANCELLED'],
  SUBMITTED: ['APPROVED', 'REJECTED', 'DRAFT'],
  APPROVED: ['RELEASED', 'CANCELLED'],
  REJECTED: ['DRAFT'],
  RELEASED: ['PART_SUPPLIED', 'CLOSED', 'CANCELLED'],
  PART_SUPPLIED: ['CLOSED', 'CANCELLED'],
  CLOSED: [],
  CANCELLED: [],
};

const VEHICLE_STATUS_TRANSITIONS = {
  IN_TRANSIT: ['ARRIVED'],
  ARRIVED: ['RECEIVED', 'EXCEPTION'],
  RECEIVED: ['RECEIPT_ACCEPTED', 'HOLD', 'EXCEPTION'],
  EXCEPTION: ['RECEIVED', 'HOLD'],
  RECEIPT_ACCEPTED: ['PDI_PENDING'],
  HOLD: ['PDI_PENDING', 'RECEIPT_ACCEPTED', 'RECTIFICATION'],
  PDI_PENDING: ['PDI_PASS', 'PDI_FAIL', 'PDI_HOLD'],
  PDI_PASS: ['AVAILABLE'],
  PDI_FAIL: ['PDI_PENDING', 'WORKSHOP'],
  PDI_HOLD: ['PDI_PENDING', 'WORKSHOP'],
  AVAILABLE: ['RESERVED', 'DEMO', 'DISPLAY', 'TEST_DRIVE', 'BLOCKED'],
  RESERVED: ['AVAILABLE', 'BOOKED'],
  BOOKED: ['INVOICED', 'AVAILABLE'],
  INVOICED: ['DELIVERY_READY'],
  DELIVERY_READY: ['DELIVERED'],
  DELIVERED: [],
  BLOCKED: ['AVAILABLE', 'WORKSHOP'],
  DAMAGED: ['WORKSHOP', 'BLOCKED'],
  WORKSHOP: ['PDI_PENDING', 'AVAILABLE', 'BLOCKED'],
  DEMO: ['AVAILABLE'],
  DISPLAY: ['AVAILABLE'],
  TEST_DRIVE: ['AVAILABLE'],
};

const PDI_RESULTS = [
  'PASS',
  'FAIL',
  'PASS_WITH_OBSERVATION',
  'RECTIFICATION_REQUIRED',
  'TECHNICAL_HOLD',
  'OEM_HOLD',
];

const RECEIPT_STATUSES = ['ACCEPTED', 'ACCEPTED_WITH_OBSERVATION', 'HOLD', 'REJECTED'];

const RECTIFICATION_STATUSES = [
  'OPEN',
  'ASSIGNED',
  'WIP',
  'WAITING_PARTS',
  'WAITING_OEM',
  'COMPLETED',
  'RE_PDI_PENDING',
  'CLOSED',
];

const HOLD_REASONS = [
  'TECHNICAL',
  'DAMAGE',
  'OEM_CAMPAIGN',
  'DOCUMENTATION',
  'BATTERY',
  'COMMERCIAL',
  'MANAGEMENT',
  'INSURANCE',
  'OTHER',
];

const AGEING_BUCKETS = ['0-15', '16-30', '31-45', '46-60', '61-90', '90+'];

const ORDER_STAGES = [
  'DRAFT',
  'AWAITING_STOCK',
  'ALLOCATED',
  'PAYMENT',
  'INSURANCE',
  'REGISTRATION',
  'FINAL_PDI',
  'RETAIL',
  'INVOICED',
  'DELIVERY_READY',
  'DELIVERED',
  'CANCELLED',
];

module.exports = {
  PO_STATUSES,
  LEGACY_PO_RAISED,
  LEGACY_PO_PARTIAL,
  VEHICLE_STATUSES,
  LEGACY_STOCK_STATUSES,
  PO_STATUS_TRANSITIONS,
  VEHICLE_STATUS_TRANSITIONS,
  PDI_RESULTS,
  RECEIPT_STATUSES,
  RECTIFICATION_STATUSES,
  HOLD_REASONS,
  AGEING_BUCKETS,
  ORDER_STAGES,
};
